### ISSUE TITLE
Change mention of DockerHub

### ISSUE THREAD

**Issue by Roxedus** [unraid/webgui#780]
Now that other registries are gaining traction, and people and organizations moving away from DockerHub (for hopefully obvious reasons) I would like this string to be platform-independent.

I don't quite know how intricate changing the string actually is, I would imagine it would be just updating the referenced line. 

https://github.com/limetech/webgui/blob/684be9dd0d050113e5c2d2cb0e6f47512b85d271/plugins/dynamix.docker.manager/include/CreateDocker.php#L813

**Comment by Squidly271** [comment]
2 options.  You can change the text there AND on line 37 in https://github.com/unraid/lang-en_US/blob/master/docker.txt 

or you can leave the first alone and add in "replacement text" after the equal sign in the 2nd.  No "simple" solution due to translations being present.

First option winds up removing any translations for the line already done and substituting English, whereas the second option doesn't and makes the English match the concept you're trying to convey but leaves the translations solely referencing dockerHub

**Comment by Roxedus** [comment]
I would ideally opt for option 1, as that would be technically correct, however I do see the implications. I think I'm going to leave this as a issue then, as I do not see this as my decision to make.

Is there a process or better a suited place for discussing changes like this that would break translations?

**Comment by Squidly271** [comment]
You do whatever PR(s) you're comfortable with, then the comments happen upon it and @limetech makes the decision.

**Comment by djerfy** [comment]
Update done (https://github.com/limetech/webgui/pull/1216/files). This issue can be closed.

**Comment by ljm42** [comment]
Thanks
